### ISSUE TITLE
plz add netstandard2.0  for net framework 

### ISSUE THREAD

**Issue by IOL0ol1** [nilsauf/RxSerialPort#91]
https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0

As a nuget package, 
```xml
<TargetFrameworks>netstandard2.0; netstandard2.1</TargetFrameworks> 
```
is perhaps the most perfect. 

However, only netstandard2.0 dependencies are added to System.Reactive, at least we can add netstandard2.0 to support net461+

**Comment by nilsauf** [comment]
Hi! 
I dont even remember, why i did not include .net Standard 2.0/2.1...

I am on parental leave right now, so I dont know if I find time to investigate. 
Feel free to have a go and open a pull request!

cheers

**Comment by nilsauf** [comment]
Version 1.2.2 should be available soon
